### ISSUE TITLE
Payload too large, no tx handling

### ISSUE THREAD

**Issue by friedger** [blockstack/stacks-local-dev#13]
I see errors in the log of the fellower...

```
mocknet_stacks-node-follower | ERRO [1612356223.617695] [testnet/stacks-node/src/event_dispatcher.rs:102] [main] Event dispatcher: POST mocknet_stacks-node-api.mocknet:3700 failed with error Response { status: PayloadTooLarge, headers: Headers { headers: {HeaderName("content-length"): [HeaderValue { inner: "144" }], HeaderName("x-powered-by"): [HeaderValue { inner: "Express" }], HeaderName("connection"): [HeaderValue { inner: "keep-alive" }], HeaderName("x-content-type-options"): [HeaderValue { inner: "nosniff" }], HeaderName("content-type"): [HeaderValue { inner: "text/html; charset=utf-8" }], HeaderName("date"): [HeaderValue { inner: "Wed, 03 Feb 2021 12:43:43 GMT" }], HeaderName("content-security-policy"): [HeaderValue { inner: "default-src \'none\'" }]} }, version: None, sender: Some(Sender { .. }), receiver: Receiver { .. }, body: Body { reader: "", length: Some(144) }, local: TypeMap }
```

and in the api:
```
mocknet_stacks-node-api | PayloadTooLargeError: request entity too large
mocknet_stacks-node-api |     at readStream (/app/node_modules/raw-body/index.js:155:17)
mocknet_stacks-node-api |     at getRawBody (/app/node_modules/raw-body/index.js:108:12)
mocknet_stacks-node-api |     at read (/app/node_modules/body-parser/lib/read.js:77:3)
mocknet_stacks-node-api |     at jsonParser (/app/node_modules/body-parser/lib/types/json.js:135:5)
mocknet_stacks-node-api |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
mocknet_stacks-node-api |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
mocknet_stacks-node-api |     at /app/node_modules/express/lib/router/index.js:284:7
mocknet_stacks-node-api |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
mocknet_stacks-node-api |     at next (/app/node_modules/express/lib/router/index.js:275:10)
mocknet_stacks-node-api |     at /app/node_modules/@promster/express/dist/modules/middleware/middleware.js:59:16
mocknet_stacks-node-api |     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
mocknet_stacks-node-api |     at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)
mocknet_stacks-node-api |     at /app/node_modules/express/lib/router/index.js:284:7
mocknet_stacks-node-api |     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
mocknet_stacks-node-api |     at next (/app/node_modules/express/lib/router/index.js:275:10)
mocknet_stacks-node-api |     at expressInit (/app/node_modules/express/lib/middleware/init.js:40:5)
```

When sending a deploy tx to the miner node, I see the contract being deployed, however, the corresponding tx is not found when querying the api node.

## Steps to reproduce
1. Start local-dev after applying #9 and #12 
2. Check the logs
2. Send a deploy tx
3. Check the logs
4. Query the api node for the tx

**Comment by friedger** [comment]
Setting `use_test_genesis_chainstate = true` worked for me.

**Comment by wileyj** [comment]
> Setting `use_test_genesis_chainstate = true` worked for me.

Where did you set this value?

**Comment by wileyj** [comment]
wouldn't this be addressed by using the feat-mock-miner image?
https://github.com/blockstack/stacks-blockchain/blob/56c77a3f5d0e6cad79b36d1bdb8e4918d580c261/testnet/stacks-node/src/genesis_data.rs

**Comment by wileyj** [comment]
I think this is what you're looking for?
https://github.com/blockstack/stacks-local-dev/blob/master/stacks-node-follower/Config.toml.template#L5
https://github.com/blockstack/stacks-local-dev/blob/master/stacks-node-miner/Config.toml.template#L7

**Comment by friedger** [comment]
Not an issue anymore :-)
