### ISSUE TITLE
Add replay file capability for the API

### ISSUE THREAD

**Issue by wileyj** [blockstack/stacks-local-dev#50]
Upgrading the API when there are schema changes results in errors like this:
```
{
  "error": "error: column \"execution_cost_read_count\" does not exist",
  "stack": "error: column \"execution_cost_read_count\" does not exist\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (events.js:400:28)\n    at addChunk (internal/streams/readable.js:293:12)\n    at readableAddChunk (internal/streams/readable.js:267:9)\n    at Socket.Readable.push (internal/streams/readable.js:206:10)\n    at TCP.onStreamRead (internal/stream_base_commons.js:188:23)",
  "errorTag": "567978f0-2131-45a0-8f8d-ee9920caba81"
}
```

currently this repo does not account for replay events. let's do the needful and make that possible

**Comment by wileyj** [comment]
this has been PR'ed
